name: firestore_repository_pattern
description: Application scaffold for efficient firestore usage including pagination.
version: 0.9.0
homepage: https://github.com/oleo65/firestore-repository-pattern

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^6.0.0
  flutter_hooks: ^0.21.0
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^3.0.0-dev.17
  hooks_riverpod: ^3.0.0-dev.17

  flutter:
    sdk: flutter

dev_dependencies:
  freezed: ^3.0.0
  build_runner: ^2.0.6
  riverpod_generator: ^3.0.0-dev.17

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
